# Generated by Django 5.1.3 on 2026-09-15 10:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfqs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quotation_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('validity_date', models.DateField(help_text='Offer valid until')),
                ('delivery_days', models.PositiveIntegerField(default=7, help_text='Committed delivery timeframe in days')),
                ('payment_terms', models.CharField(default='Net 30 Days', help_text='e.g. 100% Advance, Net 30, 50% Advance / 50% Delivery', max_length=150)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted (Awarded)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Delivery conditions, warranty, commercial terms')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfqs.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['grand_total', 'delivery_days', '-created_at'],
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotation_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.CharField(blank=True, help_text='Brand model, warranty, lead time notes', max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='rfqs.rfqitem')),
            ],
            options={
                'unique_together': {('quotation', 'rfq_item')},
            },
        ),
    ]
