# Generated by Django 5.1.3 on 2026-09-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_license_number', models.CharField(help_text='UAE Commercial License / DED Number', max_length=100)),
                ('tax_registration_number', models.CharField(blank=True, help_text='Federal Tax Authority TRN (15 digits)', max_length=50)),
                ('industry', models.CharField(default='General Commerce & Logistics', max_length=100)),
                ('contact_person_designation', models.CharField(default='Procurement Manager', max_length=100)),
                ('emirate', models.CharField(choices=[('DUBAI', 'Dubai'), ('ABU_DHABI', 'Abu Dhabi'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QUWAIN', 'Umm Al Quwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], default='DUBAI', max_length=50)),
                ('office_address', models.TextField(help_text='Building, Street, Area, Dubai/UAE')),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
