services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - SECRET_KEY=django-insecure-procurehub-demo-docker-secret-key-dubai-2026
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgres://procurehub:procurehub123@db:5432/procurehub_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=procurehub_db
      - POSTGRES_USER=procurehub
      - POSTGRES_PASSWORD=procurehub123
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
