# Generated by Django 5.1.3 on 2026-09-15 10:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
        ('rfqs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('po_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delivery_address', models.TextField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=30)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='quotations.quotation')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='rfqs.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Pcs', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('delivery_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('supplier_rating_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payment_terms_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_recommended', models.BooleanField(default=False)),
                ('recommendation_rationale', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='RFQAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('award_reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True, help_text='Commercial / Technical evaluation notes')),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awarded_rfqs', to=settings.AUTH_USER_MODEL)),
                ('awarded_quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='quotations.quotation')),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='rfqs.rfq')),
            ],
        ),
    ]
