# Generated by Django 5.1.3 on 2026-09-15 10:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_plan', models.CharField(choices=[('FULL', '100% Full Payment'), ('ADVANCE_BALANCE', 'Advance (40%) + Delivery Balance (60%)'), ('INSTALLMENTS', '3 Structured Installments (33% / 33% / 34%)')], default='ADVANCE_BALANCE', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=64)),
                ('gateway_provider', models.CharField(default='Mock Telr/Stripe UAE Service', max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.payment')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
