# Generated by Django 5.1.3 on 2026-09-15 10:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_license_number', models.CharField(help_text='UAE Commercial License / DED Number', max_length=100)),
                ('trade_license_document', models.FileField(blank=True, help_text='PDF or Image copy of UAE Trade License', null=True, upload_to='trade_licenses/')),
                ('business_categories', models.CharField(default='Office Furniture, IT Equipment, Commercial Supplies', help_text='Comma-separated business capabilities', max_length=255)),
                ('emirate', models.CharField(choices=[('DUBAI', 'Dubai'), ('ABU_DHABI', 'Abu Dhabi'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QUWAIN', 'Umm Al Quwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], default='DUBAI', max_length=50)),
                ('office_address', models.TextField(help_text='Warehouse / Showroom address in UAE')),
                ('years_in_business', models.PositiveIntegerField(default=5)),
                ('supplier_rating', models.DecimalField(decimal_places=2, default=Decimal('4.80'), help_text='Supplier performance rating (1.00 - 5.00)', max_digits=3)),
                ('completed_orders_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified DED/FTA supplier badge')),
                ('tax_registration_number', models.CharField(blank=True, help_text='FTA TRN', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='Emirates NBD', max_length=150)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
